blivedm:
    server: ws://blivechat:12450/api/chat
    roomid: 26949229
textouthttp:
    server: ""
    droprate: 0
live2d:
    driver: http://live2ddriver:9004/driver
    forwarder: http://live2ddriver:9002/live2d
chatbot:
    musharing:
        disabled: false
        server: musharing_chatbot:50051
    chatgpt:
        disabled: false
        server: chatgpt_chatbot:50052
        configs:
            - version: 3
              apikey: sk-xxx
              initialprompt: "you are muli, an AI VTuber live streaming."
        cooldown: 15
sayer:
    server: externalsayer:50010
    role: default
listen:
    textinhttp: 0.0.0.0:51080
    audiocontrollerws: 0.0.0.0:51081
readdm: true
reduceduration: 5
toolongdontsay: 500
